export const ActionTypes = {
    ALL_DISH: "ALL_DISH",
    GET_DISH: "GET_DISH",
    GET_INGREDIENTS : "GET_INGREDIENTS",
    GET_INGREDIENT: "GET_INGREDIENT",
    SEARCH_ALLITEMS : "SEARCH_ALLITEMS",
    ADD_DISH: "ADD_DISH",
}